title: draw.io libraries for semantic web domain
description: Libraries of diagrams and shapes from the semantic web domain for draw.io. To make it easy for people to reuse diagrams seen in resources such as PROV and Graffoo.
theme: minima
permalink: pretty
